import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { ViewProvider } from "@/components/view-context";
import { AiAgentModal } from "@/components/ai-agent-modal";
import { FloatingAgentButton } from "@/components/floating-agent-button";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ViewProvider>
            <Navbar />
            <AiAgentModal />
            <FloatingAgentButton />
            <main className="pt-16 min-h-screen">
              {children}
            </main>
          </ViewProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
