import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { ViewProvider } from "@/components/view-context";
import { AiAgentModal } from "@/components/ai-agent-modal";
import { FloatingAgentButton } from "@/components/floating-agent-button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="antialiased">
        <ThemeProvider>
          <ViewProvider>
            <Navbar />
            <AiAgentModal />
            <FloatingAgentButton />
            <main className="min-h-screen pt-16 app-shell">{children}</main>
          </ViewProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
